version: '3'

tasks:
  build:
    cmds:
      - gofmt -w .
      - go build --tags=llvm14 .
      - ./glamlang {{.CLI_ARGS}}
  test:
    cmds:
      - go test ./tests -v
  lint:
    cmds:
      - golangci-lint run
